on:
  push:
    paths:
      - ".forgejo/workflows/test*.yml"
      - "**/*.rs"
      - "**/*.el"
      - "Cargo.*"
      - "Makefile*"
      - "configure*"
  pull_request:

jobs:
  check:
    runs-on: docker
    container: node:alpine3.24
    steps:
      - uses: actions/checkout@v6
      - run: |
          apk update
          apk add emacs rust rust-clippy rustfmt
      - name: Test
        run: |
          ./configure
          make check -kj
