on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jcs090218/setup-emacs@v3
        with:
          version: 29.2
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install rustc rust-clippy rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: |
          ./configure
          make check
      - name: Compile
        run: |
          mkdir opt
          make install PREFIX=opt
          cd opt
          tar -cvf rag.tar *
          xz rag.tar
      - uses: actions/upload-artifact@v4
        with:
          path: opt/rag.tar.xz
