on:
  push:
  pull_request:

jobs:
  rust_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cargo_subcommand:
          - build
          - check
          - clippy
          - fmt --check
          - test
        include:
          - cargo_subcommand: clippy
            extra_packages: rust-clippy
          - cargo_subcommand: fmt
            extra_packages: rustfmt
    steps:
      - uses: actions/checkout@v6
      - run: |
          sudo apt-get install -y cargo rustc ${{ matrix.extra_packages }}
      - name: Test
        run: |
          cargo ${{ matrix.cargo_subcommand }}
