on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.17.0
        with:
          components: "clippy, rustfmt"
      - uses: purcell/setup-emacs@v3
      - run: make check
